const SELLERS = [{
        name: "Summit Chain Co",
        url: "https://www.temu.com/mall.html?mall_id=741070853378563",
        avatar: "img/fc55b73b.webp",
        badges: ["local", "star", "packGood"],
        sold: "30K+",
        rating: 4.7,
        reviews: 3727,
        shipping: "Free",
        bars: [90, 3, 1, 1, 5]
    },
    {
        name: "TCG Empire",
        url: "https://www.temu.com/mall.html?mall_id=741070852035508",
        avatar: "img/b28882e0.webp",
        badges: ["local", "star", "packGood"],
        sold: "150K+",
        rating: 4.6,
        reviews: 25795,
        shipping: "$30 min order",
        bars: [83, 5, 3, 2, 7]
    },
    {
        name: "MEGACARDS",
        url: "https://www.temu.com/mall.html?mall_id=741070851925183",
        avatar: "img/d7c49111.webp",
        badges: ["local", "star", "packBad"],
        sold: "150K+",
        rating: 4.6,
        reviews: 20502,
        shipping: "$30 min order",
        bars: [84, 5, 3, 2, 6]
    },
    {
        name: "Larry's Card Mart",
        url: "https://www.temu.com/mall.html?mall_id=741070851918312",
        avatar: "img/594dc3b2.webp",
        badges: ["local", "star", "packGood"],
        sold: "92K+",
        rating: 4.8,
        reviews: 13922,
        shipping: "$30 min order",
        bars: [92, 3, 1, 1, 3]
    },
    {
        name: "manditogonTCG",
        url: "https://www.temu.com/mall.html?mall_id=741070853640394",
        avatar: "img/2b0a6cb3.webp",
        badges: ["local", "star", "packGood"],
        sold: "3.8K+",
        rating: 4.9,
        reviews: 450,
        shipping: "Free",
        bars: [94, 2, 0, 1, 3]
    },
    {
        name: "Collectors Emporium",
        url: "https://www.temu.com/mall.html?mall_id=741070851660908",
        avatar: "img/4634d8c5.webp",
        badges: ["local", "star", "packGood"],
        sold: "100K+",
        rating: 4.7,
        reviews: 8615,
        shipping: "$30 min order",
        bars: [90, 4, 2, 1, 4]
    },
    {
        name: "MANT TCG",
        url: "https://www.temu.com/mall.html?mall_id=741070853718556",
        avatar: "img/67dfc197.webp",
        badges: ["local", "star", "packGood"],
        sold: "3.5K+",
        rating: 4.8,
        reviews: 348,
        shipping: "$30 min order",
        bars: [92, 2, 3, 1, 2]
    },
    {
        name: "HAUSE of Toys & Collectibles",
        url: "https://www.temu.com/mall.html?mall_id=741070852380709",
        avatar: "img/97b3b7af.webp",
        badges: ["local", "packGood"],
        sold: "67K+",
        rating: 4.8,
        reviews: 6239,
        shipping: "$30 min order",
        bars: [91, 3, 1, 1, 4]
    },
    {
        name: "Turbo TCG inc",
        url: "https://www.temu.com/mall.html?mall_id=741070853221313",
        avatar: "img/40f25798.webp",
        badges: ["local", "packBad"],
        sold: "6.5K+",
        rating: 4.8,
        reviews: 774,
        shipping: "$30 min order",
        bars: [93, 2, 1, 1, 3]
    },
    {
        name: "VMG Enterprise",
        url: "https://www.temu.com/mall.html?mall_id=741070853026788",
        avatar: "img/1668dc04.webp",
        badges: ["local", "packGood"],
        sold: "3.3K+",
        rating: 4.8,
        reviews: 449,
        shipping: "Free",
        bars: [92, 3, 0, 0, 5]
    },
    {
        name: "CBTCG",
        url: "https://www.temu.com/mall.html?mall_id=741070852824195",
        avatar: "img/3b1bc2cb.webp",
        badges: ["local", "packGood", "packBad"],
        sold: "1.8K+",
        rating: 4.9,
        reviews: 187,
        shipping: "Free",
        bars: [95, 2, 1, 1, 2]
    },
];

const PROMOS = [
  {
    id: "claimgift",
    name: "Free Gift(s)",
    codes: ["claimgift"],
    accepts: ["Credit", "Discounts"],
    payout: ["Gift", "Coupons"],
    type: ["Daily claim", "Coupon Bundle"],
    date: "2024-07-07",
    terms: "How To Play\n\nStep 1: Users will get $40 Gift(s) as rewards through cracking golden eggs, etc. Subject to a minimum purchase depends on the value of the gifts chosen.\nStep 2: After place an order on the activity page, users can get the $0 Gift(s)\n\n[...]\n\nTHE PROMOTION. By opening the Promotion page, or clicking on the \"Sign in to get\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, after placing an order with an actual payment amount over a designated amount as displayed on the Promotion page (the \"Minimum Payment Amount\") within the Time Limit (\"Qualifying Order\"), a Member is entitled to get free item(s), which shall be picked by the Member from the Promotion page before placing the Qualifying Order, as well as a $100.00 (Max) coupon bundle (\"Rewards\"). The actual payment amount aforesaid means the actual payment amount paid by the Member after applying any discounts or other benefits applicable to the transaction, and taxes and shipping fees are excluded. After payment of the Qualifying Order, Members shall visit the Promotion page and click \"grab\" (expression may vary) to manually claim the free item(s) before the expiration date as displayed on the Promotion page. Free item(s) that are not claimed before the expiration date will be forfeited. Only one free item can be claimed per day. All the coupons will expire at 24:00 the day after they are claimed. General rules regarding coupons set by Temu will apply. If a Member cancels or applies for a refund for any Qualifying Order, in whole or in part, and as a result the total price of such Qualifying Order drops below the Minimum Payment Amount, then such Qualifying Order will be canceled and the Rewards will be taken back. If any Rewards are not issued due to Sponsor's reasons (e.g., the free item(s) are out of stock, etc.), Members are entitled to repick the Rewards or, if repicking is not possible, receive a coupon or Temu credits of the same amount as the selling price (not the strikethrough prices) of the unissued Rewards.\n\nThe interface displayed on the Promotion page may simulate interactive functions such as \"jackpot\", \"wheel\", \"gift box\" and \"cards\" for illustrative purposes only. These interactive functions do not involve any form of chance, auctions or contests, and their results are based on objective criteria, i.e., everyone will get the best result in such interactive functions. The number of Rewards a Member can receive is subject to the Promotion page, and the value of the Rewards may vary.\n\nTIME LIMIT. The “Time Limit” for the Promotion will be displayed on the Promotion page.",
    reward: "Pick free items one at a time. 3-4 Gifts + Coupons",
    rules: [
      { t: "Pick your gifts on the promo page before you buy anything. Slots open one at a time (seen: 3 picks, then a mystery 4th)" },
      { t: "That last slot is coupons, not a gift. Worth 100% of a qualifying order (seen: $20 min spend, $100 max)" },
      { t: "Check the ⓘ before you buy. The \"$100\" is really a pile of coupons with high minimums (seen: 3×$15 off $135, 4×$10 off $100, 3×$5 off $60)", warn: true },
      { t: "Place an order above the minimum before time runs out" },
      { t: "The minimum is what you actually pay after discounts. Tax and shipping explicitly don't count", warn: true },
      { t: "One gift claim per day. Coupons are 24h expiry." },
      { t: "Refunding below the minimum kills the order and all your rewards", warn: true },
    ],
    updated: "Rules last updated July 7, 2024",
    images: [
      { src: "img/323ffed9.webp", caption: "Picking the 2nd gift, 3rd still locked" },
      { src: "img/42daec4c.webp", caption: "Picking the 3rd gift, mystery box is next" },
      { src: "img/4be8da21.webp", caption: "4th slot: it's coupons, not a gift ($20 min order)" },
      { src: "img/1d8dc716.webp", caption: "Ready to check out with $100 coupons back" },
      { src: "img/3678ffe4.webp", caption: "What the $100 bundle actually contains" },
    ],
  },
  {
    id: "rebate100",
    name: "Buy and Get Coupon Bundle",
    codes: ["rebate100"],
    accepts: ["Credit", "Discounts"],
    payout: ["Coupons"],
    type: ["Coupon Bundle"],
    date: "2024-11-12",
    terms: "[...]\n\nTHE PROMOTION. By clicking the \"Spin\" button (expression may vary) or entering the Promotion page, you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member can earn the coupon bundle described on the Promotion page (\"Rewards\") by purchasing over a certain number of products as displayed on the Promotion page within the Time Limit. The products purchased must be selected from the Promotion page. The combinations of the coupons included in the Rewards will be displayed on the Promotion page. The Member will get one of the combinations as displayed on the Promotion page. The conditions of Rewards (such as the expiration time and application scope) for each coupon will be displayed on it after receipt. General rules about the Rewards set by Temu will also apply. If a Member cancels or applies for a refund for any item in the order placed in the Promotion, the Rewards will be taken back. Members may be subject to shipping fees if purchasing items not shipped from Temu.\n\nThe interface displayed on the Promotion page (if any) may simulate a \"jackpot\", \"wheel\", \"gift box\" or \"cards\", the functions of which are for illustrative purposes only. This Promotion does not involve any form of chance, auctions, or contests and is based on objective criteria, i.e., everyone will get the best result in such functions.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is displayed on the Promotion page.",
    reward: "Several types of Coupon bundles, good and bad.",
    rules: [
      { t: "Has two flavors: Bad version: Coupon bundle in return for purchasing x items in an order. Better version: Coupon bundle (with considerably better numbers) and a much lower minimum item order." },
      { t: "Buy however many items the page says (seen: 1 or 2) before time runs out" },
      { t: "Tap the ? on the bundle first to see what you're actually getting" },
      { t: "The big number is misleading. It's mostly coupons like $50 off a $300+ order (seen: $50 off $300, $30 off $200, etc.)", warn: true },
      { t: "You won't see expiry dates or restrictions until after you get the coupons", warn: true },
      { t: "After you qualify, it will nag you to place another order for a \"boost\" (seen: one more 2-item order for +$300). Same deal, tap the ⓘ first" },
      { t: "Whether the boost is worth it depends on the order minimums. $300 in coupons that need $140 to $420 orders is not $300", warn: true },
      { t: "Boost coupons usually have a 7-day expiry (seen)" },
      { t: "Refund anything in the order and all coupons are gone", warn: true },
    ],
    updated: "Rules last updated November 12, 2024",
    images: [
      { src: "img/837e9c98.webp", caption: "$422 version (buy 1 item)" },
      { src: "img/aae333f4.webp", caption: "$602 version (buy 2 items)" },
      { src: "img/f1704180.webp", caption: "What's actually inside the bundle" },
      { src: "img/8979be51.webp", caption: "After the first order: Boost to $722 with one more 2-item order" },
      { src: "img/e6e128ff.webp", caption: "What the $300 boost actually is: nine coupons needing $140 to $420 orders" },
      { src: "img/a212adf1.webp", caption: "Vanilla flavor, worse version!" },
    ],
  },
  {
    id: "stargift000",
    name: "[Free Gift(s) with Eligible Purchases]",
    codes: ["star gift000"],
    accepts: ["Credit", "Discounts"],
    rating: "bad",
    payout: ["Gift", "Coupons"],
    type: ["Coupon Bundle"],
    date: "2026-01-15",
    terms: "By clicking on the \"Spin\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member is entitled to take a certain number of items picked from the Promotion page for free (\"Rewards\") when the Member has successfully accumulated enough \"stars\" within the Time Limit. The number of stars required for each Reward will be clearly displayed next to the item on the Promotion page. Once the Member picks the Reward(s), they cannot change them. In addition, for the first order, the Members may receive a coupon bundle worth 100% of their first order value (excluding taxes, shipping fees, or any additional charges) (the \"Coupon Bundle\"). Members can earn stars based on the following rules: For each order that meets the minimum spend requirement shown on the Promotion page (a \"Qualifying Order\"), the Member will receive stars equal to a certain percentage of the price shown on the list of items in each subsequent order. The order amount refers to the total selling price of the items in the Qualifying Order, as displayed on the Promotion page, and excludes applicable taxes, shipping fees, and any additional charges. For certain order(s), Members may receive stars at a higher percentage rate, subject to a maximum cap on the total stars that can be earned from such order(s). When the stars earned from a Qualifying Order are sufficient to redeem a Reward, the redeemed Reward will be shipped together with that Qualifying Order.\n\nThe total value of the Coupon Bundle for the first order is capped at $100. The combinations of the coupons included in the Rewards will be displayed on the Promotion page. The number of the coupons in the Reward as well as the conditions of use, which may include purchase amount thresholds and coupon values, will be displayed on the Promotion page. Other conditions (such as the expiration time) for each coupon will be displayed on it after receipt. For the avoidance of doubt, to get the Rewards, the Member shall first pick the free item(s) and then include the free item(s) in the Qualifying Order before the Member places such Qualifying Order. When the stars earned from a Qualifying Order are sufficient to redeem a Reward, the redeemed Reward will be shipped together with that Qualifying Order. If a Member cancels or applies for a refund for any Qualifying Order, in whole or in part, and as a result the total price of such Qualifying Order drops below the minimum requirement or reduces the stars earned such that they are no longer sufficient for the redeemed Reward(s), then such Qualifying Order will no longer qualify for the Promotion and the Reward(s) will be canceled. If the canceled Reward has not yet been shipped, it will be removed from the order. If the canceled Reward has already been shipped, the Member may be charged the full price of the Reward.\n\nThe interface displayed on the Promotion page (if any) may simulate a \"jackpot\", \"wheel\", \"gift box\" or \"cards\", the functions of which are for illustrative purposes only. This Promotion does not involve any form of chance, auctions or contests and is based on objective criteria, i.e., everyone will get the best result in such functions.",
    reward: "Earn stars by ordering, \"trade\" them for free stuff (seen: 5 gifts up to $385). First order also gets coupons, max $100",
    rules: [
      { t: "Pick what you want on the promo page, then add it to your cart before checkout" },
      { t: "Chosen items cannot be changed once picked.", warn: true },
      { t: "Orders above the minimum earn stars, a stated % of the items' listed price" },
      { t: "Stars come from the item price only, not tax/shipping", warn: true },
      { t: "Some orders may give a boosted star rate (capped)" },
      { t: "First order also gets a coupon bundle matching its value, up to $100, mostly garbage" },
      { t: "Coupon details are on the page, but expiry dates only show up after you get them", warn: true },
      { t: "If you refund enough to drop below the minimum, all provided rewards are cancelled.", warn: true },
    ],
    updated: "Rules last updated January 15, 2026",
    image: "img/1743e09b.webp",
  },
  {
    id: "calendar1000",
    name: "TEMU Gift Calendar",
    codes: ["calendar1000", "QQQQ"],
    accepts: ["Credit", "Discounts"],
    payout: ["Coupons", "Gift"],
    type: ["Daily claim", "Coupon Bundle"],
    date: "2026-04-03",
    terms: "THE PROMOTION. By clicking on the \"Pick your ultimate gift\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member can pick an item from the Promotion page as the \"Ultimate Gift\" and earn it for free within the Time Limit after the Member (i) unlocks the Gift Calendar by placing an order over the minimum number of items required as displayed on the Promotion page; and (ii) claims all the \"Daily Gifts\" after the Gift Calendar is unlocked. The Ultimate Gift and the Daily Gifts will be referred to collectively as \"Rewards\" hereunder.\n\nThe Daily Gifts include:\n(i) Temu Credits collectively worth up to $1;\n(ii) Temu Coupons collectively worth up to $1,000 in savings; and\n(iii) A total of 7 reward items, the value of which varies depending on the Member's selection.\n\nPlease note that the displayed value of Temu Coupons awarded in the Promotion is the sum of the potential savings that a Member can realize if they use all of the Temu Coupons they receive during the Promotion after meeting the applicable requirements. For example, if a Member receives a Temu Coupon that entitles them to a $20 discount off a qualifying purchase of $50+ and a Temu Coupon that entitles them to a $40 discount off a qualifying purchase of $80+ and no other Temu Coupons, the Temu Coupons received in the Promotion will be shown to be worth $60 in savings.\n\nAll the Temu Coupons can only be used where the terms and conditions shown on the coupon are met. For example, some coupons may expire 24 hours after receipt and can only be used before the expiration time; some coupons are only applicable to items shipped from local warehouses. This is not an exhaustive list of possible limitations on using Temu Coupons; please refer to the coupons' actual instructions. Only one Temu Coupon can be used per order. Members can check the details of the coupons after receipt. Find more rules regarding Temu coupons in \"Coupons & Offers\" → \"Q&A\".\n\nTo receive the reward items, Members are required to place orders. Members may select the reward item(s) before placing order(s) on the Promotion page, so that the reward item(s) can be shipped with the order. A shipping fee and a minimum order amount may apply, as displayed on the Promotion page.\n\nMembers must claim the Daily Gift for each day within that day. If the Member fails to claim the Daily Gift for a given day, both that day's Daily Gift and the Ultimate Gift will become invalid.\n\nSome versions of the Promotion allow reclaiming previously missed Daily Gifts and pre-claiming future Daily Gifts using \"coins\" collected in the Promotion, subject to the instructions and limitations shown on the Promotion page. This feature is only available if expressly shown on the Promotion page. If applicable, coins can be collected by completing the following daily tasks as specified on the Promotion page:\n(i) Browsing designated page(s) within the Promotion for a specified period;\n(ii) Placing qualifying order(s) exceeding the required order amount within the Promotion;\n(iii) Other tasks as displayed on the Promotion page.\n\nSaid coins have no monetary value and can only be used in this Promotion to pre-claim or reclaim Daily Gifts.\n\nIf Members cancel or successfully request a refund for any order placed in the Promotion, any Gifts, Rewards, and/or coins (if applicable) earned in connection with the order, in whole or in part, will be forfeited.",
    reward: "Open daily gifts to unlock a free Ultimate Gift. The headline number is mostly coupons.",
    rules: [
      { t: "Pick your Ultimate Gift, then unlock the calendar by buying the number of items it asks for" },
      { t: "Free items need an order to ship with, so pick them first, then buy.", warn: true },
      { t: "If multiple free items are ready at once, try to grab them all in one order. You can use coins to force this." },
      { t: "Coins stack up per $ spent (seen: 1,000 per $10) with bonuses for more orders" },
      { t: "Coupon restrictions (24h expiry, local-only, etc.) are hidden until you get them. One per order", warn: true },
      { t: "Some versions let you recover missed days or pre-claim future ones using coins from daily tasks" },
      { t: "Refund any order and everything tied to it (gifts, rewards, coins) is reclaimed", warn: true },
    ],
    images: [
      { src: "img/bd93fb47.webp", caption: "Just started, calendar locked" },
      { src: "img/624f07cc.webp", caption: "Items ready to grab" },
      { src: "img/dc3c5b03.webp", caption: "All days done" },
    ],
    updated: "Rules last updated April 3, 2026",
  },
  {
    id: "rewardsback",
    name: "Full Reimbursement",
    codes: ["rewardsback"],
    accepts: ["Credit"],
    payout: ["Cash*", "Credit", "Coupons", "Discount"],
    type: ["Daily claim", "Coupon Bundle"],
    date: "2025-02-21",
    terms: "THE PROMOTION. The \"Reimbursement\" feature provides up to 100% value back through allowances, Temu credits, coupons, or items of equal value for eligible Promotion purchases. By clicking on the \"Spin Now\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member can earn the following rewards (\"Rewards\"): (1) Temu Credits, (2) Temu Coupon or Coupon Bundles, and (3) Allowance (as defined below) by purchasing selected items in the Promotion page over a designated amount within the Time Limit (the \"Qualifying Orders\"). The total value of the Rewards is the same value as the Qualifying Order and is composed of the following components: 50% in Temu Coupon or Coupon Bundles, 50% in Allowance, and an extra 30% in Temu Credits. The amount of the Rewards for each order is capped at US$130 or other amount as displayed on the Promotion page, with (1) the Temu Credits included in the Rewards capped at US$30, (2) Allowance included in the Rewards capped at US$50, and (3) Coupon Bundle included in the Rewards capped at US$50. Temu Credits may not be available instantly after placing the orders and may be subject to a delay in issuance as displayed on the Promotion page. Issuance of PayPal Cashback may be subject to additional review and delay where applicable. The coupons of a Coupon Bundle are subject to spending thresholds and time limitations as displayed on the Promotion page.\n\nCoupons and Allowance will be distributed automatically. To claim the Credits, Members shall visit the Promotion page and click on the \"Claim now\" button (expression may vary) to manually claim the Temu Credits. Credits must be claimed manually each day over 7 consecutive days, starting from 12 AM on [the day of enrollment]. Claims must be made before use. Any credits not claimed by 12 AM on [7 days after enrollment] will be forfeited.\n\nYou cannot redeem Temu Credits for cash. Temu Credits will automatically apply to your next order unless you decide not to use them. Your statutory right of withdrawal remains unaffected. Temu credits will be revoked if you cancel the orders you made to receive the Temu credits. Otherwise, the Temu credits you have claimed have no expiration date.\n\nExtra Rewards. After completing payment for the first Qualifying Order and obtaining the Rewards in accordance with the applicable Rules, a Member may be offered an opportunity to upgrade the remaining value of the Rewards to a new total value of $100, consisting of: (1) Temu Credits, (2) Temu Coupons, and (3) Promotion-page Coupons (collectively, the \"Extra Rewards\"). The Extra Rewards will be distributed as follows: 50% in Temu Coupons, 50% in Promotion-page Coupons, and 30% in Temu Credits. Except as otherwise expressly provided below for the Extra Rewards, the applicable terms and conditions governing the corresponding type of Reward set forth above in these Rules will apply to the Extra Rewards. To obtain the Extra Rewards, the Member must, within the applicable Time Limit, place and complete payment for a second Qualifying Order through the Promotion page, which must meet the applicable minimum spend requirement displayed on the Promotion page.\n\n• If a refund is issued, any unclaimed rewards and any claimed but unused rewards will be forfeited and cannot be redeemed.\n\nThe interface displayed on the Promotion page may simulate a \"treasure box\", \"gift box\" or \"cards\" for illustrative purposes only. These interactive functions do not involve any form of chance, auctions or contests, and their results are based on objective criteria, i.e., everyone will get the best result in such interactive functions.\n\n• Shipping fees may apply to products shipped from third-party providers, the amount of which will be displayed when the corresponding product is checked out.\n\n• Allowance. Allowance is a type of promotional voucher that can be used to reduce the payment amount when placing orders over designated products on the Promotion page. The Allowance is applicable only within the designated Promotion page and cannot be used for general purchases across the platform. For this promotion, the Allowance is valid for 2 hours from the time it is issued to the Member. If the Allowance is not used within this period, it will expire and cannot be redeemed or reissued. Allowance cannot be transferred, sold, or exchanged for cash. Only one Allowance can be used per order. Allowance cannot be combined with other discounts or promotions unless explicitly stated.\n\n• TIME LIMIT. The \"Time Limit\" for the Promotion is 24 hours from the time of a Member's enrollment in the Promotion or as otherwise displayed on the Promotion page.",
    reward: "Up to 100$ back on your order, split across allowances, credits and coupons",
    rules: [
      { t: "Buy from the promo page above the minimum within 24h of joining" },
      { t: "The 100% is split: 50% coupons + 50% allowance + 30% credits. Each part has its own cap" },
      { t: "Coupons and allowance show up automatically. Coupons have spend thresholds and time limits" },
      { t: "Allowance is promo-page only, one per order, and expires in ~2 hours", warn: true },
      { t: "Daily claim for the credits over ~week. If you miss a day, the rest of the days are invalidated.", warn: true },
      { t: "The page varies the number of daily installments, and the type you get each day (credits, allowance, or coupons) is random", warn: true },
      { t: "After your first order they might offer an upgrade to $100 total if you buy again in time" },
      { t: "Refunding removes all rewards and locks the promo for a cool off period.", warn: true },
    ],
    images: [
      { src: "img/e8dbb81f.webp", caption: "Before picking an item" },
      { src: "img/511c20e6.webp", caption: "After picking, tiers and daily claim shown" },
    ],
    updated: "Rules last updated February 21, 2025",
  },
  {
    id: "claimcredit",
    name: "Cash Back / Credit Back",
    codes: ["claimcredit", "credit777"],
    accepts: ["Credit", "Discounts"],
    rating: "good",
    payout: ["Cash*", "Credit"],
    type: ["Daily claim"],
    date: "2025-07-14",
    terms: "THE PROMOTION. By clicking on the \"Grab Now\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). A Member can obtain a specified amount (as displayed on the Promotion page) of Temu credits (\"Rewards\") according to such Member's payment amount (excluding taxes, coupons or Temu credits applied to such order, as well as shipping costs) according to the following rules:\n\n** AMOUNTS IN THIS TABLE CHANGE, EXAMPLE ONLY **\n<table><thead><tr><th>Order Amount (X)</th><th>The Value of Rewards Back (Y)</th></tr></thead><tbody><tr><td>X ≤ $10</td><td>Y=10%*X</td></tr><tr><td>$10 ≤ X ≤ $280</td><td>Y=50%*(X-$10)+$1</td></tr><tr><td>X > $280</td><td>Normally:<br>Y=135%*(X-$280)+$136<br>Limited-time offer:<br>Y=220%*(X-$280)+$136</td></tr><tr><td colspan=2>The rate of the Rewards is as displayed on the Promotion page.<br>The value of the Rewards is capped at a certain amount as displayed on the Promotion page.<br>A Member is eligible to claim the Rewards for the order upon successful payment for such order.<br>If a Member cancels or applies for a refund for any item in the order placed in the Promotion, then the Rewards will be taken back.</td></tr></tbody></table>\n\nFollowing a qualifying purchase, a Member may be presented with a limited-time opportunity to place an additional qualifying order. This additional qualifying order allows the Member to unlock the remaining Rewards not yet earned under the Promotion, if it is completed within the applicable time limit and meets the minimum purchase amount requirement displayed on the Promotion page. Upon successful completion of the additional qualifying order, the Member's total Rewards will include both the Rewards earned from the initial qualifying order and the Rewards unlocked through the additional qualifying order, up to the maximum eligible reward amount under the Promotion, with instalment amounts adjusted accordingly. Participation in this additional opportunity is optional and will not affect the Rewards already earned from the initial qualifying order. The Rewards are issued as Temu credits. A Member is eligible to claim the Temu credits for the order upon successful payment for such order. Temu credits cannot be redeemed for cash. Temu credits will automatically apply to the Member's next order unless the Member decides not to use them. Temu credits will be revoked if the Member cancels the orders the Member made to receive the Temu credits. Otherwise, the Temu credits the Member has claimed have no expiration date.\n\nIf one or more products in an order that has qualified a Member for the reward are cancelled or successfully refunded such that the order(s) no longer meet(s) the amount necessary to qualify for the Rewards, except when the refund is due to product quality issues or incorrect or defective items, Sponsor will revoke the Temu Credits that have been issued to the Member in the Promotion. Members understand that, if they spend Temu Credits before the cancellation or the completion of the refund, their non-reward Credits will be spent first. When the cancellation or refund is completed, Temu will deduct Temu Credits in the amount of the issued Credits from the Member's balance, determined at the point of completion but without counting the refund amount (or all remaining Credits if said balance is below that amount). Such deduction will not cause the balance to become negative and the refund amount will not be impacted.\n\nMembers become eligible to claim Rewards upon confirmation of successful payment for Qualifying Orders. The confirmation of the Rewards will take a few days to proceed, no longer than 90 days. To collect the Rewards, Members must manually claim Rewards in 10 consecutive daily instalments by visiting the Promotion page and clicking \"Claim Now\" (or similar wording). A Member can collect only one instalment per day for each order, the amount of which is displayed on the Promotion page. Any instalment of the Rewards that is not claimed on the corresponding date as displayed on the Promotion page will be void. If a Member applies for a refund of any order placed in the Promotion, then all the unclaimed Rewards for such order will be void. The interface displayed on the Promotion page (if any) may simulate a \"jackpot\", \"wheel\", \"gift box\" or \"cards\", the functions of which are for illustrative purposes only. This Promotion does not involve any form of chance, auctions or contests and is based on objective criteria, i.e., everyone will get the best result in such functions.",
    reward: "Get back a % of what you spend, paid out in 10 daily installments. Can be cash",
    rules: [
      { t: "Tiered rates. Each % only applies to the dollars in that bracket, not your whole order" },
      { t: "Tax, shipping, coupons and credits don't count toward the total", warn: true },
      { t: "Capped at whatever max the page shows. Rates and caps change between offers", warn: true },
      { t: "Officially it's \"credits,\" but the page often lets you take cash to PayPal instead." },
      { t: "You have to come back 7-10 days in a row to claim each installment.", warn: true },
      { t: "Miss a day, that installment is gone. There are no mechanisms to recover missed days in this promo!", warn: true },
      { t: "They might offer a second order to unlock whatever's left if your initial order wasn't the full amount. Totally random." },
      { t: "Refund anything and they invalidate all installments plus already-issued credits (quality/defective issues exempt)", warn: true },
    ],
    calc: {
      note: "Plug in your numbers: reward = tier 1 rate × amount up to cap 1 + tier 2 rate × next bracket + tier 3 rate × the rest, capped at your max",
      fields: [
        { k: "cap", label: "Max reward", value: "180" },
        { k: "x", label: "Order amount", value: "300" },
        { k: "c1", label: "Tier 1 up to", value: "10" }, { k: "r1", label: "Tier 1 %", value: "10" },
        { k: "c2", label: "Tier 2 up to", value: "280" }, { k: "r2", label: "Tier 2 %", value: "50" },
        { k: "r3", label: "Tier 3 %", value: "220" },
      ],
      out: "reward",
      f: `(() => {
        const y = v => Math.min(v,c1)*r1/100 + Math.max(0, Math.min(v,c2)-c1)*r2/100 + Math.max(0, v-c2)*r3/100;
        const t1 = c1*r1/100, t2 = t1 + (c2-c1)*r2/100;
        const need = cap <= t1 ? cap/(r1/100) : cap <= t2 ? c1 + (cap-t1)/(r2/100) : c2 + (cap-t2)/(r3/100);
        return "$" + Math.min(y(x), cap).toFixed(2) + " · full $" + cap + " needs $" + need.toFixed(2) + " spend";
      })()`,
    },
    updated: "Rules last updated July 14, 2025",
    images: [
      { src: "img/bad01116.webp", caption: "Tiers hidden" },
      { src: "img/7dab7493.webp", caption: "Tiers revealed" },
      { src: "img/b65deac1.webp", caption: "Day-by-day claiming (done)" },
    ],
  },
  {
    id: "credit8888",
    name: "Temu Credit Back",
    codes: ["credit8888"],
    accepts: ["Credit", "Discounts"],
    payout: ["Credit"],
    type: ["Daily claim"],
    date: "2026-09-04",
    terms: "THE PROMOTION. By clicking on the \"Spin\" button (expression may vary) or entering the Promotion page, you agree to enroll as a member of the Promotion (\"Member\"). To participate in the Promotion, a Member must first unlock the Promotion by placing an initial order on the Promotion page exceeding the required order amount within the Time Limit (\"Initial Order\").\n\nOnce the Promotion is unlocked, a Member may place up to 20 qualifying orders on the Promotion page within 7 days after unlocking, with a maximum of 5 qualifying orders per day. For each qualifying order placed under the Promotion, a Member can earn Temu Credit back (\"Rewards\") based on the order amount and the applicable credit back rate as displayed on the Promotion page. Different portions of an order amount may be calculated using different credit back rates. All orders placed under the Promotion are subject to the minimum order amount displayed on the Promotion page.\n\nThe amount of Rewards a Member can earn from each qualifying order is calculated based on a tiered structure according to the order amount of each qualifying order:\n\nOrders 1–20 (Rounds 1–20)\nOrder Amount (X) → The Value of Rewards Back (Y)\n• $0 ≤ X ≤ $10 → Y = 10% × X\n• $10 < X ≤ $60 → Y = 40% × (X − $10) + $1\n• X > $60 → Y = 100% × (X − $60) + $21\n\nOrder Amount (X) refers to the order value after applying discounts, Temu Coupons, Temu Credits and excluding shipping fees, taxes, and any other applicable fees. The Rewards are capped at a maximum amount as displayed on the Promotion page. Once the cap is reached, no more Rewards will be given on that qualifying order. Each qualifying order corresponds to one independent round. Rounds will become available sequentially, and a Member must complete the current round before the next round becomes available.\n\nThe Rewards awarded from each qualifying order will be divided into 7 installments and must be manually claimed on the Promotion page for 7 consecutive days after the successful payment for the qualifying order. The amount of Rewards a Member can claim per day will be displayed on the Promotion page and will be forfeited if it is not claimed within that day.\n\nTemu Credits cannot be redeemed for cash and will automatically apply to the Member's future orders unless they decide not to use them. Find more rules regarding Temu Credits in \"Credit balance\" → \"About Temu Credit balance\". The issuance of the Rewards will take a few days to proceed, but no longer than 90 days.\n\nIf a Member applies for a refund of the Initial Order or any qualifying order placed in the Promotion, the Rewards earned from that order will be taken back, and the Member may be disqualified from the Promotion for 90 days, or for such other period as may be determined by the Sponsor.\n\nThe interface displayed on the Promotion page (if any) may simulate a \"wheel\", \"gift box\", \"cards\" or \"gold eggs\", the functions of which are for illustrative purposes only. This Promotion does not involve any form of chance, auctions, or contests and is based on objective criteria, i.e., everyone will get the best result in such functions.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is displayed on the Promotion page.\n\nCONDITIONS. Sponsor reserves the right to substitute a Reward of equal or greater value (e.g., Temu credits or Temu coupons), including, without limitation, when a Reward is no longer available. Rewards may only be available while supplies last. Restrictions and additional rules may apply.",
    reward: "Credit back on up to 20 orders in 7 daily claims.",
    rules: [
      { t: "Unlock it first with an order over the page minimum before the timer runs out (seen: $6.99 min, 24h timer, plus $3 credit for unlocking)" },
      { t: "Then up to 20 more orders from the promo page within 7 days, max 5 a day. Every order is its own round and the next one doesn't open until you finish the current one" },
      { t: "Tiered rates per order (seen: 10% on the first $10, 40% from $10 to $60, 100% on everything past $60). Each rate only applies to the dollars in that bracket" },
      { t: "The order value used for the promo is the final cost, not including taxes, shipping, and fees." },
      { t: "Capped per order at whatever max the page shows (seen: $50). Once you hit it, the rest of that order earns nothing", warn: true },
      { t: "Each order's credit is split into 7 daily installments you claim by hand for 7 days straight. Miss a day and that day's chunk is gone", warn: true },
      { t: "Refunds or cancellations related to this promo explicitly give your account a 90-day ban from getting it again!", warn: true },
    ],
    calc: {
      note: "Credit Back Calculator:<br>NUMBERS VARY! Find your numbers from the \"Rules\" in the top right of the page!",
      tpl: [
        "CAP ${cap} Credit back × 20 Chances",
        "$0 ≤ X ≤ ${c1} → Y = {r1}% × X",
        "${c1} < X ≤ ${c2} → Y = {r2}% × (X − ${c1}) + {=t1}",
        "X > ${c2} → Y = {r3}% × (X − ${c2}) + {=t2}",
        "Order Amount (X): ${x}",
      ],
      fields: [
        { k: "cap", label: "Max credit back per order", value: "50.00" },
        { k: "c1", label: "Tier 1 up to", value: "10.00" },
        { k: "r1", label: "Tier 1 rate %", value: "10", step: "1" },
        { k: "c2", label: "Tier 2 up to", value: "60.00" },
        { k: "r2", label: "Tier 2 rate %", value: "40", step: "1" },
        { k: "r3", label: "Tier 3 rate %", value: "100", step: "1" },
        { k: "x", label: "Order Amount (X)", value: "6.99" },
      ],
      derived: { t1: "c1*r1/100", t2: "c1*r1/100 + (c2-c1)*r2/100" },
      out: "Rewards Back (Y):",
      f: `(() => { const y = Math.min(x,c1)*r1/100 + Math.max(0, Math.min(x,c2)-c1)*r2/100 + Math.max(0, x-c2)*r3/100; const t1 = c1*r1/100, t2 = t1 + (c2-c1)*r2/100; const need = cap <= t1 ? cap/(r1/100) : cap <= t2 ? c1 + (cap-t1)/(r2/100) : c2 + (cap-t2)/(r3/100); return !isFinite(y) ? "—" : "$" + Math.min(y, cap).toFixed(2) + (y >= cap ? " (capped at CAP)" : isFinite(need) ? " (an order of $" + need.toFixed(2) + " hits CAP)" : ""); })()`,
    },
    updated: "Rules last updated September 4, 2026",
    images: [
      { src: "img/b2a531cc.webp", caption: "$50 x 20 version. $6.99 to unlock, $3 credit thrown in" },
    ],
  },
  {
    id: "wincash",
    name: "Place Orders to Win Credits and Cash Back",
    codes: ["wincredit", "wincash"],
    accepts: ["Credit", "Discounts"],
    rating: "good",
    payout: ["Cash*", "Credit"],
    type: ["Cashout"],
    date: "2025-11-17",
    terms: "THE PROMOTION. By clicking on the \"Spin Now\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member is entitled to receive the Temu credits back (\"Credit Rewards\") or cash back (\"Cash Rewards\", together with the Credit Reward, the \"Rewards\") as designated on the Promotion page by making sufficient progress to fill the progress bar. The value required to fill the progress bar may vary. A Member will make progress equal to a certain percentage as displayed on the Promotion page of the payment amount (excluding any taxes and shipping fees) of any Qualifying Order after the Member has completed the payment. A \"Qualifying Order\" means an order placed by a Member for products selected by the Member from the Promotion page within the Time Limit. The progress that can be made with respect to a Qualifying Order may be capped as indicated on the Promotion page. A Member may also make progress through certain activities that do not require purchases. The Member is entitled to claim the Rewards when the progress bar is filled within the Time Limit. The interface displayed on the Promotion page may simulate a \"treasure box\", \"gift box\" or \"cards\" for illustrative purposes only. These interactive functions do not involve any form of chance, auctions or contests and are based on objective criteria, i.e., everyone will get the best result in such interactive functions.\n\nISSUANCE OF REWARDS. The Temu credits will be issued to your credit balance. The issuance process may take several days to complete but will not exceed 90 days after you confirm receipt of each order.\nIn the event that one or more of the products purchased that qualified a Member to receive the Rewards (i) become unavailable, (ii) undergo a price adjustment, (iii) are cancelled or successfully refunded, such that the order amount falls below the amount necessary to qualify for Rewards, Sponsor reserves the rights to refuse to issue or to retrieve any previously issued corresponding Rewards and to reduce the Member's progress proportionately. If a product is cancelled or successfully refunded in said manner, except when the refund is due to product quality issues or incorrect or defective items, Sponsor will revoke the Temu Credits that have been issued to the Member in the Promotion. Members understand that, if they spend Temu Credits before the cancellation or the completion of the refund, their non-reward Credits will be spent first. When the cancellation or refund is completed, Temu will deduct Temu Credits in the amount of the issued Credits from the Member's balance, determined at the point of completion but without counting the refund amount (or all remaining Credits if said balance is below that amount). Such deduction will not cause the balance to become negative and the refund amount will not be impacted.\nAfter receiving the cash reward, Members will be eligible to participate in the Promotion only for rewards in Temu Credits during a designated cooling period.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is 3 days from the time of the Member's enrollment in the Promotion or as otherwise displayed on the Promotion page.",
    reward: "Fill a progress bar to unlock cash or credit. Page picks a random minspend",
    rules: [
      { t: "Buy from the promo page. Each order adds a % to the progress bar" },
      { t: "If you don't qualify with a single order, the next one might have a worse \"Cash Balance\" rate! (The opposite is also true)", warn: true },
      { t: "Extremely rare flavors: Single-order progress can be capped, but usually aren't. Some \"free activities\" also add a little but are almost never seen." },
      { t: "Fill the bar before time runs out, then claim. The timer may or may not be real. If it's fake, it'll run out and then refresh to be the duration of the entire promo." },
      { t: "The page has a Remaining spent ⓘ that shows roughly how much more you need. If you can't find it, leave and re-enter the promo." },
      { t: "Items going out of stock, repricing, or refunds below threshold may mean that rewards are cancelled and progress is cut, but this really only applies when multiple orders are used to qualify.", warn: true },
      { t: "Refunds revoke issued credits (unless it's a quality/defective issue). Cash is exempt by nature, but don't try to literally scam Temu please.", warn: true },
      { t: "If you complete the promo, you're stuck with one of two states: credit-only versions (cash version only), or being temporarily banned from the promo entirely. Cooloffs people have hit: 1h, 24h, 48h, 1 week, 3 weeks" },
    ],
    calc: {
      note: "Total Spend Calculator:",
      formula: `C<sub>total</sub> − C<sub>confirmed</sub> = C<sub>remaining</sub> | (C<sub>remaining</sub> − B<sub>extra</sub>) ÷ P<sub>back</sub> = $$$`,
      tpl: [
        "${c} confirmed | ${x} in cash/credit back to withdraw all",
        "🪙 {r}% Balance Back + EXTRA ${y}",
      ],
      fields: [
        { k: "c", label: "Confirmed", value: "346.50" },
        { k: "x", label: "To withdraw all", value: "3.50" },
        { k: "r", label: "Balance Back %", value: "0.20" },
        { k: "y", label: "Extra", value: "2.34" },
      ],
      out: "",
      f: `(() => { const need = (x - y) / (r / 100); return !isFinite(need) ? "—" : need <= 0 ? "$0.00 (claim it!)" : "$" + need.toFixed(2); })()`,
    },
    updated: "Rules last updated November 17, 2025",
    images: [
      { src: "img/73bc47ae.webp", caption: "Credit version" },
      { src: "img/5d088cdd.webp", caption: "Cash version, locked until a first order" },
      { src: "img/027e41db.webp", caption: "Cash version, active and nearly done" },
      { src: "img/3e829aa7.webp", caption: "The tooltip showing how much more you need" },
    ],
  },
  {
    id: "discount777",
    name: "Pick One Get ??% Off",
    codes: ["discount777"],
    accepts: ["None"],
    payout: ["Discount"],
    type: [],
    date: "2024-02-06",
    terms: "THE PROMOTION. You agree to enroll as a member of the Promotion (\"Member\") by clicking the \"draw\" button on the wheel as displayed on the Promotion page (expression may vary). Members will receive the designated discount where the wheel lands (as displayed on such Member's Promotion page; such discount, the \"Reward\"). You may purchase multiple items on the Promotion Page, but you can only apply the Reward once for only one item on the Promotion page. Additional terms and conditions may apply to the Reward as displayed on the Promotion page. The Reward cannot be used with any other offers.\n\nTIME LIMIT. A Member may access the Promotion page within a 72-hour period starting from the time such Member receives a push notification for the Promotion on the Temu application. The \"Time Limit\" is displayed on the Promotion pages.",
    reward: "Spin a wheel, get a percentage off one item from the promo page",
    rules: [
      { t: "Probably discontinued and replaced by <code>double777</code> (unconfirmed)", warn: true },
      { t: "The discount applies to one item only, even if you buy several from the page" },
      { t: "Can't be stacked with any other offer"},
      { t: "You can't force this one by searching the code. It only unlocks after Temu sends your account a push notification, and you get 72 hours from then. This is why I've never seen it ):", warn: true },
      { t: "If the promo isn't available, tap the banner on the page to get redirected to <code>double777</code>" },
    ],
    updated: "Rules last updated February 6, 2024",
    images: [{ src: "img/90f2c05b.webp", caption: "Not eligible: it says expired and then tries to redirect you" }],
  },
  {
    id: "aff123",
    name: "Affiliate",
    codes: ["aff123"],
    rating: "bad",
    payout: ["Cash", "Credit"],
    type: ["Cashout"],
    reward: "Referral cash + daily check-in coins",
    rules: [
      { t: "Cash out to PayPal or use as Temu credit" },
      { t: "7-day check-in for coins" },
      { t: "Free gifts for signing up, first share, and inviting someone" },
      { t: "Referral bonus and Ranking Race unlock later" },
    ],
    image: "img/f401b730.webp",
  },
  {
    id: "GET100",
    name: "Buy and Get Coupon Back",
    codes: ["GET100", "dailycoupon100"],
    accepts: ["Credit", "Discounts"],
    rating: "good",
    payout: ["Coupons"],
    type: ["Daily claim", "Coupon Bundle"],
    date: "2024-11-12",
    terms: "THE PROMOTION. By clicking the \"Spin\" button (expression may vary) or entering the Promotion page, you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member can earn the coupon bundle described on the Promotion page (\"Rewards\") by purchasing over a certain number of products as displayed on the Promotion page within the Time Limit. The products purchased must be selected from the Promotion page. The combinations of the coupons included in the Rewards will be displayed on the Promotion page. The Member will get one of the combinations as displayed on the Promotion page. The conditions of Rewards (such as the expiration time and application scope) for each coupon will be displayed on it after receipt. General rules about the Rewards set by Temu will also apply. If a Member cancels or applies for a refund for any item in the order placed in the Promotion, the Rewards will be taken back. Members may be subject to shipping fees if purchasing items not shipped from Temu.\n\nThe interface displayed on the Promotion page (if any) may simulate a \"jackpot\", \"wheel\", \"gift box\" or \"cards\", the functions of which are for illustrative purposes only. This Promotion does not involve any form of chance, auctions, or contests and is based on objective criteria, i.e., everyone will get the best result in such functions.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is displayed on the Promotion page.",
    reward: "Buy from the page, then claim coupons daily over 14 days",
    rules: [
      { t: "Buy the required number of items from the promo page before time's up" },
      { t: "You won't see expiry dates or restrictions until after you get the coupons", warn: true },
      { t: "One tile per day for 14 days. Miss a day and you lose the rest", warn: true },
      { t: "You can <b>timeskip</b> to get your coupons early. See Tips and tricks" },
      { t: "Most of the tiles are junk with big minimum spends. The ones worth showing up for are the gold days, which are no-minimum spend coupons", warn: true },
      { t: "Refund anything and all your coupons are revoked. Price adjustments don't count.", warn: true },
    ],
    image: "img/bd4cc1dc.webp",
    updated: "Rules last updated November 12, 2024",
  },
  {
    id: "slash99",
    name: "Slash to max 99% OFF",
    codes: ["slash99"],
    accepts: ["Credit", "Discounts"],
    payout: ["Discount"],
    type: ["Cashout"],
    date: "2026-05-28",
    terms: "THE PROMOTION. By clicking on the \"Spin\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, after picking a certain number of items from the designated pool on the Promotion page, the Member is entitled to receive additional sequential discounts on these items (\"Rewards\"), subject to specific maximum discount caps as detailed on the Promotion page, within the applicable Time Limits (defined below). Subject to the Sponsor's unavailability policy set forth below, once the Members select the Rewards, they cannot change them.\n\nThe additional discounts are calculated and applied according to the following rules:\n\nEach time a Member places an order meeting the general minimum order amount requirement (as expressly detailed on the Promotion page) via the Promotion page (\"Qualifying Order\"), the selling prices of the Rewards will be further reduced at a ratio of $1 off for every $1 spent in the Qualifying Order and are applied exclusively pursuant to the mechanics of this Promotion. Discounts are automatically applied sequentially, starting from the lowest-priced selected Reward.\n\nPurchasing the first Reward requires the Member to place their first Qualifying Order. The portion of the discount generated by the first Qualifying Order that is applied specifically toward the second Reward is strictly capped at a designated amount displayed on the Promotion page; any generated discount value exceeding this single-item cap automatically rolls over to the third and fourth Rewards. Each subsequent Qualifying Order generates a strictly capped discount amount towards the remaining Rewards (unlocking maximum discounts requires a specific cumulative spend displayed on the Promotion page, subject to the specific selling prices of the selected items).\n\nIf a Member cancels or applies for a refund for any qualifying item in the first or second Qualifying Order, or in any order containing the third or fourth Rewards, leaving only the promotional Reward(s), this will result in full cancellation of that specific order and immediate termination of the Member's participation in the entire Promotion. Furthermore, if post-purchase refunds cause the Member's cumulative qualifying spend to drop below 70% of the required milestone, any order containing the discounted third or fourth Rewards will be fully canceled. Other partial refunds will proportionally reduce or fully roll back (claw back) the promotional discounts previously applied to the remaining Rewards.\n\nThe interface displayed on the Promotion page may simulate interactive functions such as \"jackpot\", \"wheel\", \"gift box\", \"cards\" and \"scratch card\" for illustrative purposes only. These interactive functions do not involve any form of chance, auctions or contests, and their results are based on objective criteria, i.e., everyone will get the best result in such interactive functions.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is displayed on the Promotion page.",
    reward: "Pick items, then spend on other stuff from the page to slash their prices, up to 99% off",
    rules: [
      { t: "Pick your items from the page's pool. Once picked, items cannot be changed!", warn: true },
      { t: "Every qualifying order knocks $1 off your picks per $1 spent, starting from the cheapest item" },
      { t: "First qualifying order unlocks the first picked item" },
      { t: "Discount toward the 2nd item is capped. Overflow rolls to the 3rd and 4th" },
      { t: "Each order after that adds a capped amount. Full discount needs the total spend shown on the page", warn: true },
      { t: "Refunding the qualifying items to try to get only the discounted picks bans you from the promo and cancels all related orders.", warn: true },
      { t: "Drop below 70% of the milestone via refunds and orders with your 3rd/4th picks get canceled", warn: true },
      { t: "Partial refunds shrink or remove discounts on whatever's left", warn: true },
    ],
    updated: "Rules last updated May 28, 2026",
    image: "img/8389a61f.webp",
  },
  {
    id: "cccccccc",
    name: "Place Orders to Win Credits Back",
    codes: ["cccccccc"],
    accepts: ["Credit", "Discounts"],
    payout: ["Credit"],
    type: ["Daily claim"],
    date: "2025-03-16",
    terms: "THE PROMOTION. By clicking on the \"Spin Now\" button (expression may vary), you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member is entitled to receive the Temu credits back (\"Credit Rewards\") upon completing the following tasks:\n\n1. Unlock Credit Rewards: Place an order exceeding the specified amount on the Promotion page to unlock the Credit Rewards.\n\n2. Collect Credit Passes: Complete the tasks shown on the Promotion page to collect Credit Passes.\n\n3. Withdraw Rewards: Use the Credit Passes to withdraw your unlocked rewards. You may collect up to 99 passes, redeemable for up to $100 in Temu Credits in total. The promotion ends earlier once you have collected 99 passes or redeemed $100 Temu Credits.\n\nThe interface displayed on the Promotion page may simulate a \"treasure box\", \"gift box\" or \"cards\" for illustrative purposes only. These interactive functions do not involve any form of chance, auctions or contests, and their results are based on objective criteria, i.e., everyone will get the best result in such interactive functions.\n\nISSUANCE OF REWARDS. The Temu credits will be issued to your credit balance. The issuance process may take several days to complete but will not exceed 90 days after you confirm receipt of each order. Usage of the reward is subject to the minimum purchase requirement on the Temu platform. In the event that one or more of the products purchased that qualified a Member to receive the Rewards (i) become unavailable, (ii) undergo a price adjustment, (iii) are cancelled or successfully refunded, such that the order amount falls below the amount necessary to qualify for Rewards, Sponsor reserves the rights to refuse to issue or to retrieve any previously issued corresponding Rewards and to reduce the Member's progress proportionately. If a product is cancelled or successfully refunded in said manner, except when the refund is due to product quality issues or incorrect or defective items, Sponsor will revoke the Temu Credits that have been issued to the Member in the Promotion. Members understand that, if they spend Temu Credits before the cancellation or the completion of the refund, their non-reward Credits will be spent first. When the cancellation or refund is completed, Temu will deduct Temu Credits in the amount of the issued Credits from the Member's balance, determined at the point of completion but without counting the refund amount (or all remaining Credits if said balance is below that amount). Such deduction will not cause the balance to become negative and the refund amount will not be impacted.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is 10 days from the time of a Member's enrollment in the Promotion or as otherwise displayed on the Promotion page.",
    reward: "Order to unlock credit, then grind tasks for Credit Passes to withdraw it (seen: $100–$150)",
    rules: [
      { t: "To qualify, order over the minimum from the promo page to unlock (seen: $12 min)" },
      { t: "Grind page tasks to collect Credit Passes. You get ~10 days from when you make your qualifying purchase", warn: true },
      { t: "To claim the full amount: collect passes. 99 max, worth up to $100* (According to the promo rules, it caps you out early if you reach $100 back, but unconfirmed)", warn: true },
      { t: "Refunds revoke any issued credits unless the refund is quality/defective issues. Non-reward credits are taken first" },
      { t: "<strong>This promo is designed to be terrible, but we can game it</strong>: For the initial qualifying order, it uses the value of the item before discounts and credits (possibly a bug), and thus you can effectively withdraw enough credits to go positive on your spend immediately", warn: true },
      { t: "Once you're qualified, scroll through the days and sum the passes to see if you'll get enough by the end. If it doesn't add up to at least 99, then you must make at least one additional purchase to get the full credit amount on one of your claim days", warn: true },
      { t: "Only make additional purchases on days where the number of bonus passes it offers is substantial (seen: +30 passes, x40 of today's passes). Don't buy any speed up passes <em>unless</em> they also provide a good amount of bonus passes", warn: true },
    ],
    updated: "Rules last updated March 16, 2025",
    images: [
      { src: "img/fda812b0.webp", caption: "$150 version (+$50 bonus)" },
      { src: "img/a69aaedd.webp", caption: "$100 version, no bonus" },
      { src: "img/08863b14.webp", caption: "Some days prompt an extra order for bonus passes (seen: +43 passes, $15 min)" },
      { src: "img/32fbb08d.webp", caption: "Some days prompt for pass multipliers (seen: 40x today's check-in passes, $15 min)" },
      { src: "img/498fd9e0.webp", caption: "Rewards come in increments to keep you coming back" },
      { src: "img/57ceabe2.webp", caption: "Corresponding pass records" },
    ],
  },
  {
    id: "double777",
    name: "Double Savings",
    codes: ["double777"],
    accepts: ["None"],
    payout: ["Discount"],
    type: ["Cashout"],
    date: "2026-07-03",
    terms: "THE PROMOTION. By clicking on the \"Shop now\" button (expression may vary) or entering the Promotion page, you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member is entitled to place orders and enjoy discount savings as displayed on the Promotion page.\n\nThe Promotion consists of two rounds and each offers items with discount savings (\"Rewards\").\n\n- In the first round, a Member may place one order before 11:59 PM (local time) on the calendar day the Promotion begins. The amount a Member saves through their first eligible order shall not exceed the Promotion page.\n\nFollowing an eligible first order, a Member may become eligible to receive a $3-value Promotion-page Coupon. The Promotion-page Coupon entitles Members to a reduction on the Member's second eligible order placed during the first round of the Promotion and will be automatically applied to that order, subject to the applicable terms and conditions shown on the coupon. The Promotion-page Coupon awarded in the Promotion will expire at 11:59 PM (local time) on the calendar day it is issued, as recorded in Temu's system. The Promotion-page Coupon can only be redeemed on a purchase that exceeds the indicated threshold (if any) or the minimum value requirement as required by the Promotion (if any), whichever is higher. It cannot be used for general purchases across the platform.\n\nThe maximum discount savings available in the second round will depend on the actual savings achieved from the Member's first eligible order in the first round, as displayed on the Promotion page. The more a Member saves on their first eligible order in the first round, the greater the potential discount savings that may become available in the second round.\n\n- The second round will start at 12:00 AM (local time) the following day and will expire 24 hours after it becomes available, as recorded in Temu's system. Only one order can be placed in the second round by each Member.\n\nPlease notice that each order placed within the Promotion should exceed the minimum order amount requirement as displayed on the Promotion page.\n\nIf a Member cancels or requests a refund for any order placed in the Promotion, whether in whole or in part, the Member may be disqualified from the Promotion. Rewards cannot be enjoyed together with other offers or promotions. Rewards can only be delivered to a deliverable address within the country/region where the Member participated in this Promotion through the corresponding Temu site for such country/region. Members shall ensure that the address provided by them to receive the Rewards is correct. Delivery failure due to incorrect address will be borne by the Members.\n\nThe interface displayed on the Promotion page (if any) may simulate a \"wheel\", \"gift box\" or \"cards\", the functions of which are for illustrative purposes only. This Promotion does not involve any form of chance, auctions or contests and is based on objective criteria, i.e., everyone will get the best result in such functions.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is as displayed on the Promotion page.",
    reward: "Two rounds of discounted items. Save more on day one and day two's discounts get bigger (seen: save $50, earn $100 extra)",
    rules: [
      { t: "<b>Round 1:</b> make a single qualifying order from the promo page before 11:59 PM local time. How much you \"save\" in Round 2 depends on how much you saved on this order, denoted by the cash number on the left" },
      { t: "While adding items to your cart to finish Round 1, you may be offered a \"bonus\" to your total savings (seen: $20, on a 15-minute timer)" },
      { t: "You may be immediately offered a partial \"bonus\" after completing Round 1 which actually takes away from your Round 2 bonus (seen: $3 off $15 min spend, expiring in 6h)", warn: true },
      { t: "<b>Round 2</b> opens at 12:00 AM local time the next day and lasts 24 hours. One order only" },
      { t: "Cancel or refund any promo order, even partly, and you are invalidated. <em>This may or may not include price adjustments!</em>", warn: true },
      { t: "Can't be combined with other offers or credit", warn: true },
    ],
    updated: "Rules last updated July 3, 2026",
    images: [
      { src: "img/8adca8c0.webp", caption: "Empty bag (seen: $7.72 of $50, $99 of $100)" },
      { src: "img/7252d55b.webp", caption: "Bag full, timed bonus added (seen: $50 of $50, extra $20)" },
      { src: "img/945aa50f.webp", caption: "Round 1 start (seen: $3 off with $15 min today, $117 tomorrow)" },
    ],
  },
  {
    id: "save7777",
    name: "Temu Coins",
    codes: ["save7777"],
    accepts: ["Credit", "Coupons", "Discounts"],
    payout: ["Discount", "Credit", "Coupons", "Gift"],
    type: ["Daily claim"],
    date: "2026-03-13",
    terms: "THE PROMOTION. By entering the Promotion page, you agree to enroll as a member of the Promotion (\"Member\"). In the Promotion, a Member can earn points (\"Temu Coins\", \"Tcoins\", \"Temu Coin\", or similar) both from orders placed across the Temu platform (\"Qualifying Orders\") and from the daily check-in on the Promotion page. More exclusions may apply from time to time. Temu Coins can only be redeemed for certain free products (\"Prizes\") and discounted products (\"Temu Coin-Eligible Products\") within this Promotion. In addition, daily check-ins may offer Members a chance to claim free items (\"Gifts\"). \"Temu Coin-Eligible Products\", \"Prizes\" and \"Gifts\" are collectively defined as \"Rewards\".\n\nFor Qualifying Orders, Members will receive $0.1 Temu Coin for every US$1 spent. Temu Coins earned from Qualifying Orders placed on the Promotion page will be credited instantly after the Member clicks the \"Claim\" button that appears immediately following a successful checkout. Temu Coins earned from Qualifying Orders placed outside the Promotion page will be credited instantly when the Member visits the Promotion page and clicks the \"Claim\" button, which credits coins for all such orders at once. Uncredited or unclaimed Temu Coins must be claimed within 24 hours of being earned, or they will expire. Members can earn up to $100 Temu Coins per day from orders. Should an order cause a Member to exceed the daily $100 Temu Coin limit, the number of Temu Coins awarded will be automatically adjusted downward to bring the day's total to precisely $100 Temu Coins.\n\nThrough daily check-ins and without using Temu Coins, Members may get a chance for designated free promotional products (\"Gifts\"). To claim a Gift, a Member must place an order that meets the minimum spending requirement with the Gift within 24 hours of selecting the Gift. Otherwise, the Gift will expire. Any Gifts that have already been claimed during previous sign-up cycles will not be available for claiming again in any future cycles. Further, the Member will earn a specified quantity of Temu Coins (as determined by Temu in its sole discretion) by daily check-in on the Promotion page. The Temu Coins earned through the daily check-in will be automatically credited to the Member's account instantly upon clicking the \"Check-in\" button. Members may receive an elevated number of Temu Coins or other additional benefits through consecutive check-ins. The Member's consecutive check-in progress will reset to Day 1 if the Member fails to complete the daily check-in on any calendar day.\n\nAll credited Temu Coins will expire at 23:59:59, thirty (30) days after the date they were credited to the account.\n\nMembers may use a specified quantity of Temu Coins as shown on the Promotion page to redeem a designated promotional item (\"Prize\") on the Promotion page. Members must place an order with the Prize item on the Promotion page within 24 hours of selecting the Prize item to claim it (minimum order amount requirements apply). If the Member does not place the qualifying order within 24 hours, the Prize will expire and the Temu Coins used for the Prize will not be refunded. If the Member cancels or returns the order containing the Prize, the Temu Coins will be refunded. Available Prizes will be refreshed periodically. Each Member is limited to redeeming only one Prize per day, but Members may repeat this process for multiple Prizes on different days. The Prize will be re-selected if the chosen Prize is out of stock or unavailable for delivery.\n\nMembers may redeem their Temu Coins for a discount on eligible products listed on the Promotion page (\"Temu Coin-Eligible Products\"). The discount shall be calculated at a rate of US$1.00 off for every ten (10) Temu Coins used, subject to the following limitations: (a) the maximum discount attainable on each Temu Coin-Eligible Product shall not exceed US$50; (b) the maximum discount rate applied to each Temu Coin-Eligible Product shall not exceed 20% of its reference price. The calculated number of Temu Coins is always rounded up to the nearest whole Temu Coin. The special pricing for Temu Coin-Eligible Products is a standalone offer and not stackable with any other promotional offers unless otherwise permitted.\n\nTemu Coins cannot be transferred, cashed out, or used outside this Promotion. Cancellation or return of any order that has earned Temu Coins may lead to the revocation of Temu Coins or Reward(s). The number of Temu Coins to be revoked will be calculated based on the refund amount and will not exceed the number of Temu Coins that the Member has received from the order, which may have been reduced due to daily limits.\n\nMinimum order amount requirements will apply. Shipping fees may apply.\n\nTIME LIMIT. The Promotion runs until it is terminated, canceled, or suspended by Sponsor in its sole discretion.",
    reward: "Earn coins from orders + check-ins, spend them on free items or discounts",
    rules: [
      { t: "$0.10 in coins per $1 spent on any Temu order. Off-page orders show up when you tap Claim" },
      { t: "Claim within 24h or they vanish. $100/day cap from orders", warn: true },
      { t: "Daily check-in gives coins with a streak bonus. Miss a day and the streak resets", warn: true },
      { t: "Coins expire after 30 days", warn: true },
      { t: "Discounts: 10 coins = $1 off, capped at $50/item and 20% of the listed price. Can't stack" },
      { t: "Prizes rotate, and out-of-stock ones get swapped daily" },
      { t: "You can also turn coins into credit ($5, needs 14 consecutive check-ins) or grab daily instant coupons (one per order)" },
    ],
    updated: "Rules last updated March 13, 2026",
    images: [
      { src: "img/3c95e43b.webp", caption: "Main page: balance, check-ins, gifts" },
      { src: "img/a971d584.webp", caption: "10% Tcoins back on everything" },
      { src: "img/de4a36f9.webp", caption: "Free prizes (cost coins)" },
      { src: "img/8a3ca2db.webp", caption: "Redeem coins for credit or coupons" },
    ],
  },
  {
    id: "puzzleJJJJ",
    name: "Collect Puzzle Pieces to Get Rewards",
    codes: ["puzzleJJJJ"],
    accepts: ["Credit", "Discounts"],
    payout: ["Credit", "Coupons", "Gift"],
    type: ["Daily claim"],
    date: "2026-07-07",
    terms: "THE PROMOTION. By clicking on the \"Spin\" button (expression may vary) or entering the Promotion page, you agree to enroll as a member of the Promotion (\"Member\"). To unlock the Promotion, a Member should first place a qualifying order on the Promotion page. Once the Promotion is unlocked, a Member is entitled to collect a certain number of puzzle pieces and redeem the reward(s) on the Promotion page within the time limit.\n\nPuzzle pieces vary by color. The available methods for collecting each type of puzzle piece will be displayed on the Promotion page and may include: (i) completing daily check-in tasks; or (ii) placing qualifying orders on the Promotion page. The number of puzzle pieces a Member can collect per day is subject to a daily cap as displayed on the Promotion page.\n\nThe number and type of puzzle pieces required to redeem each reward are shown on the Promotion page. Rewards must be redeemed and claimed in sequence as displayed. Rewards include Temu Coupon(s), Temu Credit(s) and free gift(s) (collectively, \"Rewards\"). Please note that:\n\n(i) Temu Credit Reward(s) will be automatically credited to your account after you collect the required number of the corresponding puzzle pieces and redeem the corresponding Reward. The issuance of the Temu Credit Reward(s) will take a few days to proceed, but in no event longer than 90 days. Temu Credits will automatically be applied to the Member's future orders unless the Member decides not to use them. Temu Credits cannot be redeemed for cash.\n\n(ii) Temu Coupon Reward(s) will be automatically credited to the Member's account after the Member collects the required number of the corresponding puzzle pieces and redeem the corresponding Reward. Temu Coupons can be applied to the Member's future orders placed on Temu that meet the terms and conditions shown on the Temu Coupons to reduce the payment amount but cannot be used within this Promotion. Temu Coupons awarded in the Promotion will expire at 23:59 local time on the day after being claimed by the Member from the Promotion page. Each Temu Coupon can only be redeemed on a purchase that exceeds the indicated threshold (if any) or Temu's minimum order amount requirement (if applicable), whichever is higher.\n\n(iii) For free gift Reward(s), after collecting all required puzzle pieces, the Member must place an additional qualifying order on the Promotion page for each gift to claim it. Certain taxes and shipping fees may apply.\n\nEach order placed within this Promotion is subject to the minimum order amount requirement as displayed on the Promotion page. If a Member cancels or applies for a refund for any qualifying order, in whole or in part, the puzzle pieces collected by the Member with respect to such qualifying order will be taken back. If, as a result, the Member's total puzzle pieces become insufficient for any Reward that has already been redeemed, that Reward will be canceled and taken back. Additionally, if a Member cancels or applies for a refund for the additional qualifying order used to claim a free gift Reward, that free gift Reward will also be canceled and taken back.\n\nThe interface displayed on the Promotion page (if any) may simulate a \"wheel\", \"gift box\", \"cards\" or \"gold eggs\", the functions of which are for illustrative purposes only. This Promotion does not involve any form of chance, auctions, or contests and is based on objective criteria, i.e., everyone will get the best result in such functions.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion will be displayed on the Promotion page.",
    pending: true,
    rules: [
      { t: "Seems like: Spend 50$ to get 50$ in credits. Requires an initial 10$, plus an extra 20$ for the missing blue pieces, plus a final 20$ to claim the 50$ credit." },
      { t: "The qualifying purchase uses the order amount before reductions, so a $0 purchase can qualify", warn: true },
      { t: "Bonus purchases use the final amount as the qualifying number, taxes included", warn: true },
    ],
    calc: {
      note: "How to calculate if you'll finish the promo:",
      formula: `p<sub>target</sub> − (p<sub>initial</sub> + p<sub>bonus</sub> + (d<sub>total</sub> − d<sub>missed</sub>) × r<sub>daily</sub>)`,
      rows: true,
      fields: [
        { k: "ib", label: "Initial blue", value: "5", row: "Initial", icon: "b", step: "1" },
        { k: "iy", label: "Initial yellow", value: "5", icon: "y", step: "1" },
        { k: "bb", label: "Bonus blue", value: "0", row: "Bonus", icon: "b", step: "1" },
        { k: "by", label: "Bonus yellow", value: "3", icon: "y", step: "1" },
        { k: "db", label: "Daily blue", value: "1", row: "Daily", icon: "b", step: "1" },
        { k: "dy", label: "Daily yellow", value: "2", icon: "y", step: "1" },
        { k: "d", label: "Total days", value: "20", row: "Days", tag: "total", step: "1" },
        { k: "md", label: "Days missed", value: "0", tag: "missed", step: "1" },
      ],
      out: "remaining",
      f: `(() => { const n = [ib, iy, bb, by, db, dy, d, md]; if (n.some(v => !isFinite(v))) return "—"; const dd = Math.max(0, d - md), b = Math.max(0, Math.ceil(27 - ib - bb - db * dd)), y = Math.max(0, Math.ceil(18 - iy - by - dy * dd)); if (y > 0) return "∞ (Impossible!)"; if (b) return b + " blue (" + Math.ceil(b / 6) + " additional 20$+ order(s))"; return "0! Make a final $20 purchase to get your credit!"; })()`,
    },
    updated: "Rules last updated July 7, 2026",
    images: [
      { src: "img/108d1aac.webp", caption: "The initial page, before unlocking" },
      { src: "img/2ed348a3.webp", caption: "The initial order pays pieces to start" },
      { src: "img/ee09a3f3.webp", caption: "Bonus missions pay extra pieces, like this quiz" },
      { src: "img/cd612a50.webp", caption: "Once you qualify it turns into a daily claim" },
      { src: "img/c1f23b15.webp", caption: "The initial order qualifies on the pre-credit total" },
      { src: "img/d3fc731b.webp", caption: "A bonus order qualifies on the final total" },
    ],
  },
  {
    id: "farmland",
    name: "Farmland",
    codes: ["farmland"],
    accepts: ["Credit", "Coupons", "Discounts"],
    rating: "bad",
    payout: ["Gift", "Credit"],
    type: ["Daily claim"],
    date: "2026-03-08",
    terms: "THE PROMOTION. By clicking on the \"Pick now\" (expression may vary) button on the Promotion page or registering and joining the Promotion, a user agrees to enroll as a member of the Promotion (a \"Member\"). The free products available through this Promotion are collectively referred to as \"Rewards\" (each, a \"Reward\"), which include: (1) Gifts (defined below) obtained through the Clover-Bar, and (2) Prizes (defined below).\n\nEarning Prizes via Crop Farming\n\nA Member may choose certain product(s) on the Promotion page (the \"Chosen Product(s)\") and is entitled to receive the Chosen Products for free (the \"Prize(s)\") if the Member successfully accumulates the designated value by farming and collecting the crops within the Time Limit (defined below). To farm the crops, Members need to collect water drop amounts by completing the tasks as indicated on the Promotion page and water the crops.\n\nAll unused water drop amounts will expire after the Time Limit ends. The quantity of available Water Drops is subject to a maximum threshold. If the number of Water Drops exceeds this threshold, certain excess Water Drops may only be collectible to the extent that redeemed Water Drops are actually used at the relevant time to free up available capacity. In such circumstances, Members may collect such Water Drops proportionally based on the redeemed Water Drops so used.\n\nNotwithstanding the foregoing, if the Member has successfully claimed the Prizes, the Member will not be able to further collect water drop amounts, but the unused water drop amounts will be carried over to the next round of the Promotion (if any).\n\nThe value a Member can get by farming the crops will decline within the range as displayed on the page. The maximum water drops needed to raise a crop are up to 100,000 units. The Promotion may also allow Members to earn water drops and/or other rewards through other in-Promotion games and/or tasks. The instructions and conditions are displayed on the Promotion page where applicable.\n\nEarning Gifts via the Clover-Bar\n\nMembers may also be entitled to receive a specified number of selected free item(s) (each, a \"Gift\") when Members complete the progress bar listed on the Promotion page (\"Clover-Bar\"). The combined value of all Gifts may be capped at a specified amount which will be listed on the Promotion page. To fill the Clover-Bar, Members are required to earn enough clover-points (\"Clovers\") by placing qualifying orders from the Promotion page (each, a \"Qualifying Order\") within the specified Time Limit.\n\nThe number of Clovers earned from each Qualifying Order is subject to a cap, which may vary by order and will be displayed on the Promotion page. The Qualifying Orders are subject to the minimum order threshold which will be listed on the Promotion page. Members can also earn water drops by placing Qualifying Orders within the Time Limit. The number of water drops earned from each order and other restrictions are subject to the separate \"Rules of Water Drops\".\n\nIf a Member, in whole or in part, cancels or applies for a refund for any Qualifying Order, the following shall apply: (1) if the corresponding Gift(s) have not yet been redeemed, all progress on the Progress Bar that was directly contributed by such order will be deducted; (2) if redemption of the corresponding Gift(s) has already occurred, it will be deemed forfeited.\n\nThe interface displayed on the Promotion page may simulate interactive functions such as \"jackpot\", \"wheel\", \"gift box\" or \"cards\" for illustrative purposes only. Everyone will get the best result in such interactive functions.\n\nTIME LIMIT. The \"Time Limit\" for the Promotion is as displayed on the Promotion page.",
    reward: "Water a virtual plant to 100% and get free items. Every single thing on the page wants you to buy something first",
    rules: [
      { t: "A lawless wasteland. The games, timers, prices and tiers change randomly day to day, so nothing here is guaranteed. Every corner of it wants you to spend real money on \"water\" for your \"crops\"", warn: true },
      { t: "Progress is measured in grams of water. You need thousands. A tap gives you 1 or 2" },
      { t: "The bar creeps to 99.95% and then asks you to \"collect $0.05 more\". That last bit is the whole promo. With harvests halving every time, it is unclear you can ever actually hit $100 without a very large spend", warn: true },
      { t: "Orders are the real water source. Seen: $22+ order for 15 waterings (220 to 380g), $38+ for 20 (380 to 2000g), paid out over 3 days" },
      { t: "The \"Credit Back\" version dangles $150 max but the per-item amounts are around 10% (seen: $8.50 on an $85 item)" },
      { t: "Water from orders expires 7 days after the order. Claim daily or lose it", warn: true },
      { t: "After the water days, the order reward switches to Temu credits under a dollar each. Also daily, also expire at midnight", warn: true },
      { t: "Feed the dog, dress the dog, flip puzzle tiles, water 80 times for a competition, merge vegetables. All separate daily chores for a few grams" },
      { t: "The \"draw\" and \"bonus\" games mostly need an order to unlock spins (seen: $30 min for 2 draws)" },
      { t: "Fireworks are just a visual effect you unlock by buying something. They add nothing" },
      { t: "The main prize timer runs about a month (seen: started Aug 18, 13 days left on Sep 3, so roughly 29 days). Everything else has its own shorter timer" },
      { t: "Per the rules, a crop can need up to 100,000 units of water, and the value you get for farming \"declines within a range\". In practice each harvest pays about half the last one (seen: $1, $0.50, $0.30, $0.10, $0.05), so the goalposts move exponentially", warn: true },
      { t: "Leftover water expires when the timer ends. There is also a cap on how much water you can hold", warn: true },
      { t: "Separate from water, there is a Clover-Bar filled by placing orders (seen: 1000 clovers for 3 items, capped at 30 per order, $50 min). Only promo page orders count" },
      { t: "Refund a qualifying order and its clover progress gets deducted, or the gift is forfeited if you already redeemed it", warn: true },
    ],
    updated: "Rules last updated March 8, 2026",
    images: [
      { src: "img/92188170.webp", caption: "The farm. Yes, it is a whole game" },
      { src: "img/6c3de746.webp", caption: "Water Competition: tap more than strangers" },
      { src: "img/69e03ba0.webp", caption: "Feed the dog every day or no water for you" },
      { src: "img/a902903a.webp", caption: "Pup Dress-Up. Outfits expire, naturally" },
      { src: "img/416b79a3.webp", caption: "Big Water Benefits: water 80 times for 200g" },
      { src: "img/13aa81ad.webp", caption: "7-day Puzzle: flip a tile a day" },
      { src: "img/016db7c9.webp", caption: "Farmland Merge, a second game inside the game" },
      { src: "img/33ada412.webp", caption: "Fireworks. Buy something and the water sparkles" },
      { src: "img/e59794cd.webp", caption: "Shop More Earn Water: every item has its own gram price" },
      { src: "img/f40ee04f.webp", caption: "Order to earn Credit Back: $22+ for 15 waterings, $38+ for 20, plus a tiny % as credit" },
      { src: "img/9a501a73.webp", caption: "My Order Reward: water over 3 days, then tiny credits" },
      { src: "img/41c4f85f.webp", caption: "Draw to get Water Bonus: $30 order for two spins" },
      { src: "img/4b9aa2de.webp", caption: "Clover-Bar: 1000 clovers for 3 free items, 30 clovers max per order" },
      { src: "img/c36003b6.webp", caption: "Harvest log: $1, then 50¢, 30¢, 10¢, 5¢. Each crop is worth half the last" },
    ],
  },
];